# This script will be handled by cron to run every week to report
# commits to Administrator and Professor

# get the max of 3 num
function max3()
{
	if [[ ${1} -lt ${2} ]]
	then
		if [[ ${2} -lt ${3} ]]
		then
			return ${3}
		else
			return ${2}
		fi
	else
		if [[ ${1} -lt ${3} ]]
		then
			return ${3}
		else
			return ${1}
		fi
	fi
}

# get the revprops's address of rev
# $1 is the full address of Repo
# $2 is the rev num
function getaddofrev()
{
	echo "${1}/db/revprops/$[${2}/1000]/$[${2}%1000]"
}

# get name of the log of rev
# $1 is the full address of Repo
# $2 is the rev num
function getlogofrev()
{
	REVPFILE=$(getaddofrev ${1} ${2})
	_AUTHORSVN=`sed -n '4p' ${REVPFILE}`
	_TIMESVNRAW=`sed -n '8p' ${REVPFILE}`
	_TIMESVNRA=`echo ${_TIMESVNRAW} | grep -P -o '^[^.]*'`
	_TIMESVN=`echo ${_TIMESVNRA} | sed "s/T/ /"`
	_MSGSVN=`sed -n '12p' ${REVPFILE}`
	echo "        ---------------------------------------------------------\n"
	echo "        Rev:\t${2}------Author:${_AUTHORSVN} at ${_TIMESVN}\n"
	echo "        ==>${_MSGSVN}\n"
	echo "        ---------------------------------------------------------\n"
}

# generate a head of report
LOGFILE="/home/svn/.reportlog"
cat << _EOF_ > ${LOGFILE}
Dear >>>><<<<:
    This report is generated by SVN Server last week automatically.
    Reposiitories:
_EOF_

# for every repo generate a report of log
RepoIndex=0
for RepoName in /home/svn/repositories/*
do
	if [[ ${RepoName} == '/home/svn/repositories/*' ]]
	then
		echo -e "    [SEVERE] There are no repositories on this server! " >> ${LOGFILE}
	fi
	let RepoIndex=RepoIndex+1

	# show name of Repos
	PureRepoName=`echo "${RepoName}" | grep -P -o '[_a-zA-Z][_a-zA-Z0-9]*$'`
	echo -e "    ${RepoIndex}: ${PureRepoName}" >> ${LOGFILE}
	if [[ -f "${RepoName}/db/current" && -f "${RepoName}/db/last" ]] 
	then
		let CURRENT=`cat "${RepoName}/db/current"`
		let LAST=`cat "${RepoName}/db/last"`
		let CURRENTM3=`cat "${RepoName}/db/current"`-3
		max3 ${LAST} ${CURRENTM3} 1
		OUTPUTSTART=$?
		if [[ ${CURRENT} == ${LAST} ]]
		then
			echo -e "        No update since last week" >> ${LOGFILE}
		else
			for ((i=${CURRENT};i>=${OUTPUTSTART};i--))
			do
				echo -e $(getlogofrev ${RepoName} ${i}) >> ${LOGFILE}
			done
		fi
		echo ${CURRENT} > "${RepoName}/db/last" 
	else
		echo -e "        [SEVERE] There is no current file in Repo ${PureRepoName}" >> ${LOGFILE}
	fi
done

# append the status of RAID1

LOGFILE="/home/svn/.reportlog"
cat << _EOF_ >> ${LOGFILE}
-------------------------------------------------------------------------------
    Here is the status of RAID1
_EOF_

cat /proc/mdstat | awk '{print "    " $0}' >> ${LOGFILE} 
